### ISSUE TITLE
[docs] Semantics of ops in log_potential of Alignment

### ISSUE THREAD

**Issue by vadimkantorov** [harvardnlp/pytorch-struct#44]
http://nlp.seas.harvard.edu/pytorch-struct/model.html#torch_struct.AlignmentCRF:
`Ops are 0 -> j-1, 1->i-1,j-1, and 2->i-1`

Could you please clarify what are the ops/third dimension semantics? I guess they are somehow related to weights of insertions/deletions/substitutions in levenshtein-kinded alignment, but it'd be much clearer if this was explicitly explained.

Context:
I'd like to use Alignment as a way to do CTC alignment: I have a Tx(L+1)-sized character probabilities tensor and a (t<=T)-sized ground truth sequence. I'd like to do forced alignment and find the best monotonic mapping of ground truth characters onto input probabilities (for visualization purposes).

**Comment by srush** [comment]
Hi.

I added an example CTC notebook here https://github.com/harvardnlp/pytorch-struct/blob/master/notebooks/CTC.ipynb . Let me know if that helps!


I will fix the documentation as well, but yes they correspond to insert , match and deletes. The only difference for the standard algorithm is that it allows insert and deletes to have context of where they occur.
