### ISSUE TITLE
Does not support Cuda

### ISSUE THREAD

**Issue by da03** [harvardnlp/pytorch-struct#48]
https://github.com/harvardnlp/pytorch-struct/blob/d828506dfaf110a9d7019290997aaca9d4d528ed/torch_struct/autoregressive.py#L119

Here beam is always on CPU, so if the distribution returns CUDA probabilities, then later on we'll adding floatTensor and cuda.floatTensor together. https://github.com/harvardnlp/pytorch-struct/blob/d828506dfaf110a9d7019290997aaca9d4d528ed/torch_struct/autoregressive.py#L167

**Comment by srush** [comment]
Can you send a PR? That should take the device of the potentials.

**Comment by da03** [comment]
Sure working on it now.
