### ISSUE TITLE
Bug DependencyCRF function topk

### ISSUE THREAD

**Issue by kidlestar** [harvardnlp/pytorch-struct#50]
The output is normal for the first best case, for the rest, the results are strange.
Bug test for DependencyCRF function topk()

import torch
from torch_struct import DependencyCRF

potential = torch.rand(1,2,2)
dist = DependencyCRF(potential)
print(dist.topk(3))

**Comment by srush** [comment]
Once https://github.com/harvardnlp/pytorch-struct/pull/53 is checked in, we have a fix for this.

**Comment by srush** [comment]
Should be fixed now.
