### ISSUE TITLE
Preterminal rule prob. in NeuralCFG: probably a bug?

### ISSUE THREAD

**Issue by zhaoyanpeng** [harvardnlp/pytorch-struct#52]
https://github.com/harvardnlp/pytorch-struct/blob/8608b6c6334c8e5b2a60f748ad9529cd644b27a9/torch_struct/networks/NeuralCFG.py#L46-L49
This, for every preterminal, estimates the distribution over the words in a sentence rather than over the whole vocabulary.

Is it a bug or intended to be an approximation to the true distribution? The approximation indeed saves a lot of GPU memory but I have not tested if it would cause any performance loss.

**Comment by zhaoyanpeng** [comment]
I can send a PR if it is a bug.

**Comment by srush** [comment]
Yes it sounds like a bug. Never added tests for this part of the library, it would be great to have them.
