### ISSUE TITLE
log_potentials argument shape of PCFG

### ISSUE THREAD

**Issue by Liang-Qiu** [harvardnlp/pytorch-struct#66]
In the API document, it said class **torch_struct.SentCFG** has parameter
> log_potentials (tuple) – event tuple with event shapes terms (N x T) rules (NT x (NT+T) x (NT+T)) root 

I wonder why the rule is not of the shape NT x (NT+T)?
Thanks!

**Comment by srush** [comment]
PCFG rules are of the form A -> B C . B and C might be terminals, so N x (NT + T) x (NT + T) seemed natural.

**Comment by Liang-Qiu** [comment]
That makes sense. Thank you!
