### ISSUE TITLE
Get the score of dist.topk()

### ISSUE THREAD

**Issue by wangxinyu0922** [harvardnlp/pytorch-struct#67]
The `topk()` function returns top k predictions from the distribution, how to easily get the corresponding score of each prediction? 

By the way, when sentence lengths are short and the `k` value of topk is large, how to know the number of predictions that are valid? For the example in DependencyCRF, when sentence length is 2 and `k` is 5, only the top 3 predictions are valid I think.

**Comment by srush** [comment]
Great question, I added two new functions for you, `.kmax` and `.count`. The first should give you the kmax scores and the second should give you the total number of valid parse trees.

**Comment by wangxinyu0922** [comment]
Thank you! It's very helpful. But the `self.log_potentials.ones_like(self.log_potentials)` in `.count` function should be `torch.ones_like(self.log_potentials)`. The function now gives `*** AttributeError: 'Tensor' object has no attribute 'zeros_like'`.

**Comment by srush** [comment]
Oops fixed now.
