### ISSUE TITLE
Release on PyPI?

### ISSUE THREAD

**Issue by nikitakit** [harvardnlp/pytorch-struct#94]
Is there any interest on releasing pytorch-struct (and genbmm) on the official Python Package Index?

I ran into this because I distribute my constituency parser on PyPI, and I just recently pushed a new version that depends on pytorch-struct: https://pypi.org/project/benepar/0.2.0a0/

It turns out that packages on PyPI aren't allowed to depend on packages only hosted on github, so users of my parser can't just `pip install benepar` and have it work right away.

**Comment by srush** [comment]
Oh yeah! I will do it this weekend. Sorry about that. 

Are you using genbmm? I have a faster version in TVM that I want to put out as well. But I can't figure out how to pip that yet.

**Comment by nikitakit** [comment]
> Oh yeah! I will do it this weekend. Sorry about that.

Thank you!

> Are you using genbmm? I have a faster version in TVM that I want to put out as well. But I can't figure out how to pip that yet.

I think so? I tried running with pytorch-struct installed but no genbmm, and got an error. I'm using `torch_struct.TreeCRF` with GPU if one is available.

**Comment by srush** [comment]
Hmm that might be unneeded. I'll fix that as well.

**Comment by srush** [comment]
Thanks for the kick. Released https://pypi.org/project/torch-struct/0.5/

**Comment by nikitakit** [comment]
Thank you!

I can confirm that everything works installing from PyPI, on both CPU and GPU, and genbmm isn't required anymore. I'm testing by installing my parser (`pip install benepar`) in a fresh conda environment.
